### ISSUE TITLE
Includes all the @bases

### ISSUE THREAD

**Issue by everyonesdesign** [morishitter/postcss-include#4]
When I try to process code like

``` css
.clearfix {
    /*
    * @base
    */
    clear: both;
}


.button {
    /*
    * @base
     */
    background: red;
}

.wrapper:after {
    /*
    * @include .clearfix
     */
}

.wrapper .super-link {
    /*
    * @include .button
     */
}
```

i get 

``` css
.wrapper:after {
    /*
    * @include .clearfix
     */
    clear: both;
    background: red
}

.wrapper .super-link {
    /*
    * @include .button
     */
    clear: both;
    background: red
}
```

i.e. I get both generators in both places.
The bug can be reproduced while using postcss-include either through command line call or via atcss installation and call.
