### ISSUE TITLE
Missing nested attributes when used postcss-nested

### ISSUE THREAD

**Issue by danrichman** [morishitter/postcss-include#6]
Processing [postcss-nested](https://github.com/postcss/postcss-nested) CSS like

```css
.banner-styles {
  /*
   * @base
   */
  font-weight: 1em;
  &:hover {
    color: red;
  }
  @media (min-width: 980px) {
    font-size: 1.3em;
  }
}

.banner {
  /*
   * @include .banner-styles
   */
}
```
Results in:
```css
.banner {
  /*
   * @include .banner-styles
   */
  font-weight: 1em;
}
```
It seems to be missing the nested attributes.
